icons = "awesome"
theme = { name = "native", overrides = { separator = "" } }

[[block]]
block = "cpu"
format = "{barchart} {utilization} {frequency}"
interval = 2

[[block]]
block = "focused_window"
max_width = 25

[[block]]
block = "sound"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 60
format = "%d/%m %R"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
