icons = "awesome"
theme = { name = "modern", overrides = { separator = "" } }



[[block]]
block = "nvidia_gpu"
label = "GT 1030"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "cpu"
format = "{barchart} {utilization} {frequency}"
interval = 1

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"

[[block]]
block = "sound"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 30
format = "%a %d/%m %R"

[[block]]
block = "networkmanager"
on_click = "kitty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
